version: '3'
services:
  truyum-mysql:
    image: mysql:8.0.18
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./truyumdb:/var/lib/mysql
      - ./dbscripts:/docker-entrypoint-initdb.d
      
  eureka-discovery-server:
    image: eureka-discovery-server-app
    build: eureka-discovery-server/.
    ports:
      - 8761:8761
      
  zuul-gateway:
    image: zuul-gateway-server-app
    build: zuul-gateway/.
    ports:
      - 8083:8083
  
  menu-item-service:
    image: menu-item-app
    build: menu-item/.
    ports:
      - 8092:8092
    depends_on:
      - truyum-mysql
      - eureka-discovery-server
    links:
      - truyum-mysql
      - eureka-discovery-server
  
  truyum:
    image: truyum-app
    build: angular/.
    ports:
      - 8090:80 
  
  authentication-service:
    image: authentication-app
    build: authentication/.
    ports:
      - 8091:8091
    depends_on:
      - truyum-mysql
      - eureka-discovery-server
    links:
      - truyum-mysql
      - eureka-discovery-server